spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.135.2.29:3306/springboot?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 12345678
  application:
    name: ccw-nacos-consumer #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 8.135.2.29:8848 #nacos注册中心地址